[0m23:16:16.875374 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200402E84D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200402DF620>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200428B60F0>]}


============================== 23:16:16.964765 | e25d8f6b-08b1-46e5-85db-f9df9d295a0b ==============================
[0m23:16:16.964765 [info ] [MainThread]: Running with dbt=1.9.1
[0m23:16:16.964765 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\mathe\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m23:16:47.055634 [error] [MainThread]: Encountered an error:

[0m23:16:47.061302 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\mathe\Documents\Workspace\dbt-northwind\.venv\Lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mathe\Documents\Workspace\dbt-northwind\.venv\Lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mathe\Documents\Workspace\dbt-northwind\.venv\Lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\mathe\Documents\Workspace\dbt-northwind\.venv\Lib\site-packages\dbt\task\init.py", line 324, in run
    project_name = self.get_valid_project_name()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mathe\Documents\Workspace\dbt-northwind\.venv\Lib\site-packages\dbt\task\init.py", line 278, in get_valid_project_name
    name = click.prompt("Enter a name for your project (letters, digits, underscore)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mathe\Documents\Workspace\dbt-northwind\.venv\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mathe\Documents\Workspace\dbt-northwind\.venv\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m23:16:47.077778 [debug] [MainThread]: Command `dbt init` failed at 23:16:47.076312 after 30.35 seconds
[0m23:16:47.079452 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000200402E84D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002004423D370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020043EEA330>]}
[0m23:16:47.080981 [debug] [MainThread]: Flushing usage events
[0m23:16:47.719537 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:16:54.980969 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023343E705F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000233439A2450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000233439A3770>]}


============================== 23:16:54.981480 | 9846396d-b62a-4411-a824-c2a33b679ffc ==============================
[0m23:16:54.981480 [info ] [MainThread]: Running with dbt=1.9.1
[0m23:16:54.981480 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\mathe\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt init', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m23:21:15.710550 [error] [MainThread]: Encountered an error:

[0m23:21:15.712347 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\mathe\Documents\Workspace\dbt-northwind\.venv\Lib\site-packages\dbt\cli\requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mathe\Documents\Workspace\dbt-northwind\.venv\Lib\site-packages\dbt\cli\requires.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mathe\Documents\Workspace\dbt-northwind\.venv\Lib\site-packages\dbt\cli\main.py", line 477, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\mathe\Documents\Workspace\dbt-northwind\.venv\Lib\site-packages\dbt\task\init.py", line 324, in run
    project_name = self.get_valid_project_name()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mathe\Documents\Workspace\dbt-northwind\.venv\Lib\site-packages\dbt\task\init.py", line 278, in get_valid_project_name
    name = click.prompt("Enter a name for your project (letters, digits, underscore)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mathe\Documents\Workspace\dbt-northwind\.venv\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mathe\Documents\Workspace\dbt-northwind\.venv\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m23:21:15.721583 [debug] [MainThread]: Command `dbt init` failed at 23:21:15.721085 after 260.93 seconds
[0m23:21:15.722754 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000233433193A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023343BCDBE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023343E70890>]}
[0m23:21:15.723260 [debug] [MainThread]: Flushing usage events
[0m23:21:16.311344 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:45:02.609625 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B07F3CEC30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B001083F80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B001081100>]}


============================== 18:45:02.616552 | 0019fe1d-194e-4f81-a2a6-ef2418313ca9 ==============================
[0m18:45:02.616552 [info ] [MainThread]: Running with dbt=1.9.1
[0m18:45:02.616552 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\mathe\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:48:41.165849 [debug] [MainThread]: Starter project path: C:\Users\mathe\Documents\Workspace\dbt-northwind\.venv\Lib\site-packages\dbt\include\starter_project
[0m18:48:41.212081 [info ] [MainThread]: 
Your new dbt project "northwind" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:48:41.215301 [info ] [MainThread]: Setting up your profile.
[0m18:49:26.644415 [info ] [MainThread]: Profile northwind written to C:\Users\mathe\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m18:49:26.644415 [debug] [MainThread]: Command `dbt init` succeeded at 18:49:26.644415 after 264.25 seconds
[0m18:49:26.644415 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B07F709820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B07F709C10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002B07FBAE0F0>]}
[0m18:49:26.644415 [debug] [MainThread]: Flushing usage events
[0m18:49:27.282385 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m18:49:33.896761 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002382D2BBFB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002382FB7AC60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002382C87FB00>]}


============================== 18:49:33.902229 | 76c1c4e9-9908-4745-ab93-71fc676eb29f ==============================
[0m18:49:33.902229 [info ] [MainThread]: Running with dbt=1.9.1
[0m18:49:33.904307 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\mathe\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:49:33.948067 [info ] [MainThread]: dbt version: 1.9.1
[0m18:49:33.949080 [info ] [MainThread]: python version: 3.12.1
[0m18:49:33.949080 [info ] [MainThread]: python path: C:\Users\mathe\Documents\Workspace\dbt-northwind\.venv\Scripts\python.exe
[0m18:49:33.950412 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m18:49:34.008432 [info ] [MainThread]: Using profiles dir at C:\Users\mathe\.dbt
[0m18:49:34.008432 [info ] [MainThread]: Using profiles.yml file at C:\Users\mathe\.dbt\profiles.yml
[0m18:49:34.014152 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\mathe\Documents\Workspace\dbt-northwind\dbt_project.yml
[0m18:49:34.028086 [info ] [MainThread]: adapter type: postgres
[0m18:49:34.029437 [info ] [MainThread]: adapter version: 1.9.0
[0m18:49:34.030766 [info ] [MainThread]: Configuration:
[0m18:49:34.031702 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m18:49:34.031886 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m18:49:34.032896 [info ] [MainThread]: Required dependencies:
[0m18:49:34.034082 [debug] [MainThread]: Executing "git --help"
[0m18:49:34.047985 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m18:49:34.047985 [debug] [MainThread]: STDERR: "b''"
[0m18:49:34.053586 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m18:49:34.054100 [info ] [MainThread]: Connection:
[0m18:49:34.054930 [info ] [MainThread]:   host: dpg-cu42hvij1k6c73etoii0-a.virginia-postgres.render.com
[0m18:49:34.054930 [info ] [MainThread]:   port: 5432
[0m18:49:34.056964 [info ] [MainThread]:   user: admin
[0m18:49:34.057975 [info ] [MainThread]:   database: northwind_qe10
[0m18:49:34.057975 [info ] [MainThread]:   schema: public
[0m18:49:34.058972 [info ] [MainThread]:   connect_timeout: 10
[0m18:49:34.058972 [info ] [MainThread]:   role: None
[0m18:49:34.060001 [info ] [MainThread]:   search_path: None
[0m18:49:34.060001 [info ] [MainThread]:   keepalives_idle: 0
[0m18:49:34.061009 [info ] [MainThread]:   sslmode: None
[0m18:49:34.061716 [info ] [MainThread]:   sslcert: None
[0m18:49:34.061716 [info ] [MainThread]:   sslkey: None
[0m18:49:34.064124 [info ] [MainThread]:   sslrootcert: None
[0m18:49:34.064124 [info ] [MainThread]:   application_name: dbt
[0m18:49:34.066456 [info ] [MainThread]:   retries: 1
[0m18:49:34.066456 [info ] [MainThread]: Registered adapter: postgres=1.9.0
[0m18:49:34.379122 [debug] [MainThread]: Acquiring new postgres connection 'debug'
[0m18:49:37.964166 [debug] [MainThread]: Using postgres connection "debug"
[0m18:49:37.964347 [debug] [MainThread]: On debug: select 1 as id
[0m18:49:37.964347 [debug] [MainThread]: Opening a new connection, currently in state init
[0m18:49:39.324328 [debug] [MainThread]: Postgres adapter: Got a retryable error when attempting to open a postgres connection.
1 attempts remaining. Retrying in 0 seconds.
Error:
connection to server at "dpg-cu42hvij1k6c73etoii0-a.virginia-postgres.render.com" (35.174.144.149), port 5432 failed: FATAL:  password authentication failed for user "admin"
connection to server at "dpg-cu42hvij1k6c73etoii0-a.virginia-postgres.render.com" (35.174.144.149), port 5432 failed: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

[0m18:49:40.630652 [debug] [MainThread]: Postgres adapter: Error running SQL: select 1 as id
[0m18:49:40.631653 [debug] [MainThread]: Postgres adapter: Rolling back transaction.
[0m18:49:40.631653 [debug] [MainThread]: On debug: No close available on handle
[0m18:49:40.632652 [info ] [MainThread]:   Connection test: [[31mERROR[0m]

[0m18:49:40.632652 [info ] [MainThread]: [31m2 checks failed:[0m
[0m18:49:40.634155 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\mathe\Documents\Workspace\dbt-northwind\dbt_project.yml> not found

[0m18:49:40.634155 [info ] [MainThread]: dbt was unable to connect to the specified database.
The database returned the following error:

  >Database Error
  connection to server at "dpg-cu42hvij1k6c73etoii0-a.virginia-postgres.render.com" (35.174.144.149), port 5432 failed: FATAL:  password authentication failed for user "admin"
  connection to server at "dpg-cu42hvij1k6c73etoii0-a.virginia-postgres.render.com" (35.174.144.149), port 5432 failed: server closed the connection unexpectedly
  	This probably means the server terminated abnormally
  	before or while processing the request.
  

Check your database credentials and try again. For more information, visit:
https://docs.getdbt.com/docs/configure-your-profile


[0m18:49:40.636162 [debug] [MainThread]: Command `dbt debug` failed at 18:49:40.636162 after 6.95 seconds
[0m18:49:40.636162 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m18:49:40.637188 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023830233DA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000238302312B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000238300919A0>]}
[0m18:49:40.638164 [debug] [MainThread]: Flushing usage events
[0m18:49:41.314117 [debug] [MainThread]: An error was encountered while trying to flush usage events
